"""empty message

Revision ID: 59006fb066be
Revises: 36886dad7d1a
Create Date: 2025-01-30 15:47:42.849429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59006fb066be'
down_revision = '36886dad7d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies_table.id'], name=op.f('fk_toys_table_puppy_id_puppies_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys_table')
    # ### end Alembic commands ###
