"""add pen

Revision ID: 7d4558a55c74
Revises: 
Create Date: 2025-02-03 10:22:17.517515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4558a55c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pens_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('clickable', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pens_table')
    # ### end Alembic commands ###
